spring:
  application:
    name: deal.java.project

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
    continue-on-error: true