spring:
  application:
    name: deal.java.project

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
             allow_jdbc_metadata_access: false
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
    continue-on-error: true